const heroes = [
{ heroName: 'Razor', mainAttribute: 'Agility', roles: [ 'Carry' ,'Durable','Nuker','Pusher']},
{ heroName: 'Bane', mainAttribute: 'Intelligence', roles: [ 'Support','Disabler','Nuker','Durable']},
{ heroName: 'Pangolier', mainAttribute: 'Agility', roles: [ 'Carry' ,'Nuker','Disabler','Durable','Escape','Initiator']},
{ heroName: 'Vengeful Spirit', mainAttribute: 'Agility', roles: [ 'Support','Initiator','Disabler','Nuker','Escape']},
{ heroName: 'Wraith King', mainAttribute: 'Strength', roles: [ 'Carry' ,'Support','Durable','Disabler','Initiator']},
{ heroName: 'Pudge', mainAttribute: 'Strength', roles: [ 'Disabler','Initiator','Durable','Nuker']},
{ heroName: 'Lich', mainAttribute: 'Intelligence', roles: [ 'Support','Nuker']},
{ heroName: 'Enigma', mainAttribute: 'Intelligence', roles: [ 'Disabler','Jungler','Initiator','Pusher']},
{ heroName: 'Dark Willow', mainAttribute: 'Intelligence', roles: [ 'Support','Nuker','Disabler','Escape']},
{ heroName: 'Arc Warden', mainAttribute: 'Agility', roles: [ 'Carry' ,'Escape','Nuker']},
{ heroName: 'Tidehunter', mainAttribute: 'Strength', roles: [ 'Initiator','Durable','Disabler','Nuker']},
{ heroName: 'Sniper', mainAttribute: 'Agility', roles: [ 'Carry' ,'Nuker']},
{ heroName: 'Clinkz', mainAttribute: 'Agility', roles: [ 'Carry' ,'Escape','Pusher']},
{ heroName: 'Lina', mainAttribute: 'Intelligence', roles: [ 'Support','Carry' ,'Nuker','Disabler']},
{ heroName: 'Shadow Fiend', mainAttribute: 'Agility', roles: [ 'Carry' ,'Nuker']},
{ heroName: 'Broodmother', mainAttribute: 'Agility', roles: [ 'Carry' ,'Pusher','Escape','Nuker']},
{ heroName: 'Lion', mainAttribute: 'Intelligence', roles: [ 'Support','Disabler','Nuker','Initiator']},
{ heroName: 'Necrophos', mainAttribute: 'Intelligence', roles: [ 'Carry' ,'Nuker','Durable','Disabler']},
{ heroName: 'Winter Wyvern', mainAttribute: 'Intelligence', roles: [ 'Support','Disabler','Nuker']},
{ heroName: 'Witch Doctor', mainAttribute: 'Intelligence', roles: [ 'Support','Nuker','Disabler']},
{ heroName: 'Night Stalker', mainAttribute: 'Strength', roles: [ 'Carry' ,'Initiator','Durable','Disabler','Nuker']},
{ heroName: 'Silencer', mainAttribute: 'Intelligence', roles: [ 'Carry' ,'Support','Disabler','Initiator','Nuker']},
{ heroName: 'Alchemist', mainAttribute: 'Strength', roles: [ 'Carry' ,'Support','Durable','Disabler','Initiator','Nuker']},
{ heroName: 'Oracle', mainAttribute: 'Intelligence', roles: [ 'Support','Nuker','Disabler','Escape']},
{ heroName: 'Leshrac', mainAttribute: 'Intelligence', roles: [ 'Carry' ,'Support','Nuker','Pusher','Disabler']},
{ heroName: 'Weaver', mainAttribute: 'Agility', roles: [ 'Carry' ,'Escape']},
{ heroName: 'Dark Seer', mainAttribute: 'Intelligence', roles: [ 'Initiator','Jungler','Escape','Disabler']},
{ heroName: 'Luna', mainAttribute: 'Agility', roles: [ 'Carry' ,'Nuker','Pusher']},
{ heroName: 'Ogre Magi', mainAttribute: 'Intelligence', roles: [ 'Support','Nuker','Disabler','Durable','Initiator']},
{ heroName: 'Jakiro', mainAttribute: 'Intelligence', roles: [ 'Support','Nuker','Pusher','Disabler']},
{ heroName: 'Juggernaut', mainAttribute: 'Agility', roles: [ 'Carry' ,'Pusher','Escape']},
{ heroName: 'Riki', mainAttribute: 'Agility', roles: [ 'Carry' ,'Escape','Disabler']},
{ heroName: 'Crystal Maiden', mainAttribute: 'Intelligence', roles: [ 'Support','Disabler','Nuker','Jungler']},
{ heroName: 'Pugna', mainAttribute: 'Intelligence', roles: [ 'Nuker','Pusher']},
{ heroName: 'Shadow Shaman', mainAttribute: 'Intelligence', roles: [ 'Support','Pusher','Disabler','Nuker','Initiator']},
{ heroName: 'Naga Siren', mainAttribute: 'Agility', roles: [ 'Carry' ,'Support','Pusher','Disabler','Initiator','Escape']},
{ heroName: 'Sven', mainAttribute: 'Strength', roles: [ 'Carry' ,'Disabler','Initiator','Durable','Nuker']},
{ heroName: 'Earthshaker', mainAttribute: 'Strength', roles: [ 'Support','Initiator','Disabler','Nuker']},
{ heroName: 'Mirana', mainAttribute: 'Agility', roles: [ 'Carry' ,'Support','Escape','Nuker','Disabler']},
{ heroName: 'Terrorblade', mainAttribute: 'Agility', roles: [ 'Carry' ,'Pusher','Nuker']},
{ heroName: 'Meepo', mainAttribute: 'Agility', roles: [ 'Carry' ,'Escape','Nuker','Disabler','Initiator','Pusher']},
{ heroName: 'Slardar', mainAttribute: 'Strength', roles: [ 'Carry' ,'Durable','Initiator','Disabler','Escape']},
{ heroName: 'Outworld Devourer', mainAttribute: 'Intelligence', roles: [ 'Carry' ,'Nuker','Disabler']},
{ heroName: 'Kunkka', mainAttribute: 'Strength', roles: [ 'Carry' ,'Disabler','Initiator','Durable','Nuker']},
{ heroName: 'Huskar', mainAttribute: 'Strength', roles: [ 'Carry' ,'Durable','Initiator']},
{ heroName: 'Viper', mainAttribute: 'Agility', roles: [ 'Carry' ,'Durable','Initiator','Disabler']},
{ heroName: 'Visage', mainAttribute: 'Intelligence', roles: [ 'Support','Nuker','Durable','Disabler','Pusher']},
{ heroName: 'Gyrocopter', mainAttribute: 'Agility', roles: [ 'Carry' ,'Nuker','Disabler']},
{ heroName: 'Chen', mainAttribute: 'Intelligence', roles: [ 'Support','Jungler','Pusher']},
{ heroName: 'Spirit Breaker', mainAttribute: 'Strength', roles: [ 'Carry' ,'Initiator','Disabler','Durable','Escape']},
{ heroName: 'Death Prophet', mainAttribute: 'Intelligence', roles: [ 'Carry' ,'Pusher','Nuker','Disabler']},
{ heroName: 'Slark', mainAttribute: 'Agility', roles: [ 'Carry' ,'Escape','Disabler','Nuker']},
{ heroName: 'Phoenix', mainAttribute: 'Strength', roles: [ 'Support','Nuker','Initiator','Escape','Disabler']},
{ heroName: 'Abaddon', mainAttribute: 'Strength', roles: [ 'Support','Carry' ,'Durable']},
{ heroName: 'Bounty Hunter', mainAttribute: 'Agility', roles: [ 'Escape','Nuker']},
{ heroName: 'Disruptor', mainAttribute: 'Intelligence', roles: [ 'Support','Disabler','Nuker','Initiator']},
{ heroName: 'Drow Ranger', mainAttribute: 'Agility', roles: [ 'Carry' ,'Disabler','Pusher']},
{ heroName: 'Venomancer', mainAttribute: 'Agility', roles: [ 'Support','Nuker','Initiator','Pusher','Disabler']},
{ heroName: 'Queen of Pain', mainAttribute: 'Intelligence', roles: [ 'Carry' ,'Nuker','Escape']},
{ heroName: 'Magnus', mainAttribute: 'Strength', roles: [ 'Initiator','Disabler','Nuker','Escape']},
{ heroName: 'Dragon Knight', mainAttribute: 'Strength', roles: [ 'Carry' ,'Pusher','Durable','Disabler','Initiator','Nuker']},
{ heroName: 'Underlord', mainAttribute: 'Strength', roles: [ 'Support','Nuker','Disabler','Durable','Escape']},
{ heroName: 'Ursa', mainAttribute: 'Agility', roles: [ 'Carry' ,'Jungler','Durable','Disabler']},
{ heroName: 'Templar Assassin', mainAttribute: 'Agility', roles: [ 'Carry' ,'Escape']},
{ heroName: 'Bristleback', mainAttribute: 'Strength', roles: [ 'Carry' ,'Durable','Initiator','Nuker']},
{ heroName: 'Batrider', mainAttribute: 'Intelligence', roles: [ 'Initiator','Jungler','Disabler','Escape']},
{ heroName: 'Medusa', mainAttribute: 'Agility', roles: [ 'Carry' ,'Disabler','Durable']},
{ heroName: 'Ancient Apparition', mainAttribute: 'Intelligence', roles: [ 'Support','Disabler','Nuker']},
{ heroName: 'Spectre', mainAttribute: 'Agility', roles: [ 'Carry' ,'Durable','Escape']},
{ heroName: 'Shadow Demon', mainAttribute: 'Intelligence', roles: [ 'Support','Disabler','Initiator','Nuker']},
{ heroName: 'Troll Warlord', mainAttribute: 'Agility', roles: [ 'Carry' ,'Pusher','Disabler','Durable']},
{ heroName: 'Skywrath Mage', mainAttribute: 'Intelligence', roles: [ 'Support','Nuker','Disabler']},
{ heroName: 'Anti-Mage', mainAttribute: 'Agility', roles: [ 'Carry' ,'Escape','Nuker']},
{ heroName: 'Keeper of the Light', mainAttribute: 'Intelligence', roles: [ 'Support','Nuker','Disabler','Jungler']},
{ heroName: 'Phantom Lancer', mainAttribute: 'Agility', roles: [ 'Carry' ,'Escape','Pusher','Nuker']},
{ heroName: 'Omniknight', mainAttribute: 'Strength', roles: [ 'Support','Durable','Nuker']},
{ heroName: 'Windranger', mainAttribute: 'Intelligence', roles: [ 'Carry' ,'Support','Disabler','Escape','Nuker']},
{ heroName: 'Legion Commander', mainAttribute: 'Strength', roles: [ 'Carry' ,'Disabler','Initiator','Durable','Nuker']},
{ heroName: 'Monkey King', mainAttribute: 'Agility', roles: [ 'Carry' ,'Escape','Disabler','Initiator']},
{ heroName: 'Centaur Warrunner', mainAttribute: 'Strength', roles: [ 'Durable','Initiator','Disabler','Nuker','Escape']},
{ heroName: 'Elder Titan', mainAttribute: 'Strength', roles: [ 'Initiator','Disabler','Nuker','Durable']},
{ heroName: 'Storm Spirit', mainAttribute: 'Intelligence', roles: [ 'Carry' ,'Escape','Nuker','Initiator','Disabler']},
{ heroName: 'Lycan', mainAttribute: 'Strength', roles: [ 'Carry' ,'Pusher','Jungler','Durable','Escape']},
{ heroName: 'Puck', mainAttribute: 'Intelligence', roles: [ 'Initiator','Disabler','Escape','Nuker']},
{ heroName: 'Phantom Assassin', mainAttribute: 'Agility', roles: [ 'Carry' ,'Escape']},
{ heroName: 'Rubick', mainAttribute: 'Intelligence', roles: [ 'Support','Disabler','Nuker']},
{ heroName: 'Axe', mainAttribute: 'Strength', roles: [ 'Initiator','Durable','Disabler','Jungler']},
{ heroName: 'Chaos Knight', mainAttribute: 'Strength', roles: [ 'Carry' ,'Disabler','Durable','Pusher','Initiator']},
{ heroName: 'Clockwerk', mainAttribute: 'Strength', roles: [ 'Initiator','Disabler','Durable','Nuker']},
{ heroName: 'Warlock', mainAttribute: 'Intelligence', roles: [ 'Support','Initiator','Disabler']},
{ heroName: 'Undying', mainAttribute: 'Strength', roles: [ 'Support','Durable','Disabler','Nuker']},
{ heroName: 'Nature\'s Prophet', mainAttribute: 'Intelligence', roles: [ 'Carry' ,'Jungler','Pusher','Escape','Nuker']},
{ heroName: 'Brewmaster', mainAttribute: 'Strength', roles: [ 'Carry' ,'Initiator','Durable','Disabler','Nuker']},
{ heroName: 'Sand King', mainAttribute: 'Strength', roles: [ 'Initiator','Disabler','Nuker','Escape','Jungler']},
{ heroName: 'Invoker', mainAttribute: 'Intelligence', roles: [ 'Carry' ,'Nuker','Disabler','Escape','Pusher']},
{ heroName: 'Zeus', mainAttribute: 'Intelligence', roles: [ 'Nuker']},
{ heroName: 'Treant Protector', mainAttribute: 'Strength', roles: [ 'Support','Initiator','Durable','Disabler','Escape']},
{ heroName: 'Enchantress', mainAttribute: 'Intelligence', roles: [ 'Support','Jungler','Pusher','Durable','Disabler']},
{ heroName: 'Tinker', mainAttribute: 'Intelligence', roles: [ 'Carry' ,'Nuker','Pusher']},
{ heroName: 'Doom', mainAttribute: 'Strength', roles: [ 'Carry' ,'Disabler','Initiator','Durable','Nuker']},
{ heroName: 'Morphling', mainAttribute: 'Agility', roles: [ 'Carry' ,'Escape','Durable','Nuker','Disabler']},
{ heroName: 'Ember Spirit', mainAttribute: 'Agility', roles: [ 'Carry' ,'Escape','Nuker','Disabler','Initiator']},
{ heroName: 'Earth Spirit', mainAttribute: 'Strength', roles: [ 'Nuker','Escape','Disabler','Initiator','Durable']},
{ heroName: 'Nyx Assassin', mainAttribute: 'Agility', roles: [ 'Disabler','Nuker','Initiator','Escape']},
{ heroName: 'Dazzle', mainAttribute: 'Intelligence', roles: [ 'Support','Nuker','Disabler']},
{ heroName: 'Tusk', mainAttribute: 'Strength', roles: [ 'Initiator','Disabler','Nuker']},
{ heroName: 'Lifestealer', mainAttribute: 'Strength', roles: [ 'Carry' ,'Durable','Jungler','Escape','Disabler']},
{ heroName: 'Timbersaw', mainAttribute: 'Strength', roles: [ 'Nuker','Durable','Escape']},
{ heroName: 'Faceless Void', mainAttribute: 'Agility', roles: [ 'Carry' ,'Initiator','Disabler','Escape','Durable']},
{ heroName: 'Io', mainAttribute: 'Strength', roles: [ 'Support','Escape','Nuker']},
{ heroName: 'Bloodseeker', mainAttribute: 'Agility', roles: [ 'Carry' ,'Disabler','Jungler','Nuker','Initiator']},
{ heroName: 'Beastmaster', mainAttribute: 'Strength', roles: [ 'Initiator','Disabler','Durable','Nuker']},
{ heroName: 'Lone Druid', mainAttribute: 'Agility', roles: [ 'Carry' ,'Pusher','Jungler','Durable']},
{ heroName: 'Tiny', mainAttribute: 'Strength', roles: [ 'Carry' ,'Nuker','Pusher','Initiator','Durable','Disabler']},
{ heroName: 'Techies', mainAttribute: 'Intelligence', roles: [ 'Nuker','Disabler']}
];

export default heroes;
